allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  esbuild: set this to true or false
  fastify-socket.io: set this to true or false
  node: set this to true or false
  prisma: set this to true or false
