#!/usr/bin/env node
/**
 * sync-ai.mjs -- project the shared AI brain into every per-tool spoke.
 *
 * Single source of truth: .ai/ai-manifest.json (+ the files in .ai/skills and
 * .ai/agents, scanned live). This script renders ONE canonical "shared AI block"
 * and injects it -- between <!-- AI-SYNC:START --> / <!-- AI-SYNC:END --> markers
 * -- into each tool's entry file, so Claude, OpenCode, Copilot, Gemini and
 * codeCommand all read identical read-order, rules, skills index, and pointers.
 *
 * Usage:
 *   node scripts/sync-ai.mjs            # write the block into every spoke
 *   node scripts/sync-ai.mjs --check    # verify no drift; exit 1 if any spoke stale (CI gate)
 *
 * Output is deterministic (no timestamps) so --check is a reliable drift gate.
 * Never hand-edit the generated blocks; edit .ai/ai-manifest.json and re-run.
 */

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

const read = (p) => readFileSync(join(ROOT, p), 'utf8');
const exists = (p) => existsSync(join(ROOT, p));

const manifest = JSON.parse(read('.ai/ai-manifest.json'));
const { start: START, end: END } = manifest.syncMarkers;

// Scan .ai/skills and .ai/agents dynamically
const firstHeading = (md) => {
  const m = md.match(/^#\s+(.+)$/m);
  return m ? m[1].trim() : null;
};

const scanSkills = () => {
  const dir = join(ROOT, '.ai/skills');
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .sort()
    .map((f) => {
      const title = firstHeading(readFileSync(join(dir, f), 'utf8')) || basename(f, '.md');
      return { file: `.ai/skills/${f}`, name: basename(f, '.md'), title };
    });
};

const scanAgents = () => {
  const dir = join(ROOT, '.ai/agents');
  const out = [];
  const walk = (d, rel) => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      if (e.isDirectory()) { walk(join(d, e.name), `${rel}${e.name}/`); }
      else if (e.name.endsWith('.md')) { out.push(`${rel}${basename(e.name, '.md')}`); }
    }
  };
  walk(dir, '');
  return out.sort();
};

const skills = scanSkills();
const agents = scanAgents();

// Render the canonical shared block
const rulesTable = () =>
  ['| # | Rule | What it means | Enforced by |', '|---|------|---------------|-------------|']
    .concat(manifest.rules.map((r) => `| ${r.id} | **${r.rule}** | ${r.means} | ${r.enforcedBy} |`))
    .join('\n');

const skillsTable = () =>
  ['| Skill | File |', '|-------|------|']
    .concat(skills.map((s) => `| ${s.title} | \`${s.file}\` |`))
    .join('\n');

const renderSharedBlock = () => {
  const sf = manifest.stateFiles;
  const kb = manifest.knowledgeBase;
  return [
    '<!-- GENERATED by scripts/sync-ai.mjs from .ai/ai-manifest.json. DO NOT EDIT BY HAND. Run `npm run sync-ai`. -->',
    '',
    `## Shared AI Contract (${manifest.project})`,
    '',
    `> ${manifest.authority}`,
    '',
    '### Read order -- every session, every tool',
    '',
    manifest.readOrder.map((f, i) => `${i + 1}. \`${f}\``).join('\n'),
    '',
    '### Non-negotiable rules',
    '',
    rulesTable(),
    '',
    '### Shared skills (same for every tool -- reading the doc = knowing the skill)',
    '',
    skillsTable(),
    '',
    `### Agents: ${agents.length} specialist docs in \`.ai/agents/\` (see \`.ai/CONTRACT.md\` for the roster + coordination playbook)`,
    '',
    '### Memory + knowledge base (shared by path)',
    '',
    `- Canonical memory: \`${sf.canonicalMemory}\` -- durable decisions/conventions (every tool reads AND appends here).`,
    `- Working state / history: \`${sf.projectState}\` -- update after every non-trivial session (mandatory).`,
    `- Knowledge graph: \`${kb.graph}\` -- query via graphify, not grep (rule 1). Fallback: \`${kb.graphReport}\`.`,
    '',
    '_To change any of the above: edit `.ai/ai-manifest.json` (or add a `.ai/skills/*.md`), then `npm run sync-ai`._',
  ].join('\n');
};

const BLOCK = renderSharedBlock();

// Inject into markdown spokes
const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const managed = `${START}\n${BLOCK}\n${END}`;

const injectMarkdown = (content) => {
  const re = new RegExp(`${esc(START)}[\\s\\S]*?${esc(END)}`);
  if (re.test(content)) return content.replace(re, managed);
  const lines = content.split('\n');
  const h = lines.findIndex((l) => /^#\s/.test(l));
  if (h >= 0) {
    lines.splice(h + 1, 0, '', managed, '');
    return lines.join('\n');
  }
  return `${managed}\n\n${content}`;
};

const seedMarkdown = (name) =>
  `# ${manifest.project} -- ${name}\n\n> Entry point for this AI tool. The shared contract below is generated from \`.ai/ai-manifest.json\`.\n\n`;

// Project into JSON spokes
const injectJson = (content) => {
  const j = JSON.parse(content);
  j.read_order = manifest.readOrder;
  j.rules = manifest.rules.map((r) => `${r.rule}: ${r.means} (${r.enforcedBy})`);
  j.skills = skills.map((s) => s.file);
  j._generated = 'read_order/rules/skills are generated from .ai/ai-manifest.json by scripts/sync-ai.mjs. Edit the manifest, then run `npm run sync-ai`.';
  return `${JSON.stringify(j, null, 2)}\n`;
};

// Drive every spoke
const changed = [];
const unchanged = [];

for (const tool of manifest.tools) {
  const p = tool.spoke;
  const current = exists(p) ? read(p) : null;
  let next;

  if (tool.format === 'json') {
    if (current === null) { changed.push(`${p} (MISSING JSON spoke -- create it first)`); continue; }
    next = injectJson(current);
  } else {
    const base = current !== null ? current : seedMarkdown(tool.name);
    next = injectMarkdown(base);
  }

  if (current === next) { unchanged.push(p); continue; }
  changed.push(p);
  if (!CHECK) writeFileSync(join(ROOT, p), next);
}

// Report
console.log(`sync-ai: ${skills.length} skills, ${agents.length} agents, ${manifest.tools.length} spokes.`);
if (CHECK) {
  if (changed.length) {
    console.error(`DRIFT: ${changed.length} spoke(s) out of sync with .ai/ai-manifest.json:`);
    for (const c of changed) console.error(`  - ${c}`);
    console.error('Run `npm run sync-ai` to regenerate.');
    process.exit(1);
  }
  console.log('OK: all spokes in sync.');
} else {
  console.log(`updated: ${changed.length ? changed.join(', ') : '(none)'}`);
  console.log(`unchanged: ${unchanged.length}`);
}
